meta: {v: 1.0, source: "chat_pipeline/PIPELINE.md (condensed)"}

purpose: Convert raw chat exports to normalized, chunked format for search/analysis/context

dirs:
  10_exported/: "stage 0 - raw exports by platform"
  20_preprocessed/: "optional multi-chat splits"
  30_converted/: "stage 2 - v2.0 schema JSON"
  40_histories/: "stage 4 - final chunked histories"

final_structure: |
  40_histories/{platform}/{platform}_{YYYYMMDD}_{uuid8}_{title_slug}/
    {dirname}.001.yml
    _intermediate/  (provenance)
    _source/        (→ 10_exported)

stages:
  0_export:
    method: manual
    chatgpt: "Settings → Data controls → Export"
    claude: "claude-exporter tool or manual"
    output: 10_exported/{platform}/

  1_split:
    script: chat_export_splitter.py
    loc: bin/python/src/ai_utils/chat_processing/
    input: single JSON all conversations
    output: individual JSON per conversation

  2_convert:
    script: chat_converter.py
    input: platform-native JSON/Markdown
    output: v2.0 schema JSON/YAML
    formats: [ChatGPT JSON, Claude JSON, Markdown, HTML share pages]

  3_chunk:
    script: chat_chunker.py
    input: v2.0 schema YAML
    output: ".001.yml, .002.yml, etc"
    target_size: ~4000 tokens
    preserves: Q&A coherence

  4_organize:
    script: process_stage4.py
    loc: ai_general/scripts/chat_pipeline/
    input: 30_converted/{platform}/
    output: 40_histories/{platform}/

naming:
  directory: "{platform}_{YYYYMMDD}_{uuid8}_{title_slug}/"
  chunk: "{dirname}.{NNN}.{ext}"
  extension: {chatgpt: yml, claude: yaml}
  title_slug: "max 50 chars, lowercase, underscores"

scripts:
  chatgpt_tree_converter.py: tree exports → v2 YAML
  process_to_histories.py: chunk + organize year/month
  rename_histories.py: bulk rename to convention
  validate_v2_json.py: v2.0 schema compliance
  count_chunks.py: count chunks across dirs

schema:
  location: ai_general/docs/50_schemas/chat_history_v2.0.yml
  versions: [2.0, 2.1 (with thinking)]
  fields: [schema_version, chat_id, platform, title, created_at, updated_at, messages[role/content/thinking/timestamp]]
