meta: {v: 1.0.0, created: 2025-11-24, status: design, maintainer: PianoMan}

overview: Auto-recovery from broken chats. Detects context exhaustion, provides countdown with controls, executes recovery to continue in fresh chat.

trigger:
  detection: log monitors "prompt is too long" in claude.ai-web.log
  notification: {title: "Chat Continuity Recovery", msg: "Initiating in XX seconds...", elements: [countdown, Pause, Cancel, Continue, HTTPS/claude:// URLs]}

recovery_sequence:
  1_export: ClaudeExporter or Puppeteer → JSON/MD
  2_condense: AI generates condensed_chat_{id}.md
  3_digest: AI generates faux_context_digest_{id}.md (thinking blocks, decisions, task state)
  4_download: files → ai_memories/40_digests/chat_mems/
  5_future: rewind to 70%, replay prompts, generate true Context Digest (not_implemented)
  6-9_new_chat: create project chat → attach files → write continuation prompt → submit

components:
  notification_ui: {options: [Terminal app, Web UI, AppleScript dialog, Menu bar], recommend: "AppleScript MVP, web UI v2"}
  export: {options: [ClaudeExporter extension, Puppeteer CDP, API if available]}
  ai_processing: {options: [ChatGPT/Claude API, Web UI automation, claude CLI]}

dependencies:
  existing: [chatUrl.py, detectBrokenChat.sh, brokenChatDaemon.sh, chat_orchestrator]
  needed: [notification UI, export trigger, AI processor, continuation injector]

open_questions:
  - ClaudeExporter programmatic trigger?
  - Which AI for processing? (cost vs reliability)
  - macOS interactive notification handling?
  - Desktop app vs web UI for new chat?
  - Reliable chat_id extraction?
