meta: {v: 3.0, updated: 2026-01-01, arch: "multi-repo AI-centric", status: active}

external:
  repo: https://github.com/shillis13/ai_docs
  mount: ai_general/docs/ IS submodule
  access: https://raw.githubusercontent.com/shillis13/ai_docs/main/<path>
  purpose: cross-platform doc access (iOS, Web, other AIs)

physical_layout:
  root: ~/Documents/AI/ai_root/
  dirs:
    ai_chat_artifacts/: mirrors 40_histories structure
    ai_chatgpt/: ChatGPT-specific repo
    ai_claude/: Claude-specific repo
    ai_comms/: communication and task coordination
    ai_general/: shared resources across AIs
    ai_memories/: central memory pipeline

top_level:
  ai_chat_artifacts:
    purpose: artifacts from chats (images, docs, data)
    structure: "{ai}/YYYY/MM/DD/"

  ai_chatgpt:
    purpose: ChatGPT config, instructions, memories
    subdirs: [ai_specific_memories/, ai_scripts/, connectors/, custom_gpts/, instructions/, specs/]

  ai_claude:
    purpose: Claude config, instructions, memories
    subdirs: [ai_specific_memories/, ai_scripts/, connectors/, instructions/, skills/, specs/]

  ai_cline:
    purpose: Cline CLI workspace (local agentic AI via llama-server)
    subdirs: [config/, instructions/, memories/, work/, logs/]

  ai_claude_cli:
    purpose: Claude CLI agent workspace
    subdirs: [agents/, config/, extensions/, instructions/, memories/, work/]

  ai_codex:
    purpose: Codex CLI workspace
    subdirs: [config/, work/]

  ai_general:
    purpose: shared resources, docs, tools
    subdirs:
      data/: schemas, shared data structures
      docs/: architecture, concept docs
      instructions/: universal instructions (versioned)
      projects/: project-specific docs
      prompts/: reusable prompt library
      research_and_reports/: research outputs
      scripts/: shared automation
      specs/: technical specifications

  ai_memories:
    purpose: central memory pipeline - exports → indexed memories
    subdirs:
      10_exported/: raw exports by platform
      20_preprocessed/: preprocessing stage
      30_converted/: YAML conversion output
      40_histories/: chunked YAML archives (terminal), _chat_index.csv
      60_decisions/: architecture decisions (immutable)
      60_knowledge/: reusable facts, know_*.md articles
      70_milestones/: capability milestones
      _incoming/: intake staging (chats/, digests/)

  ai_comms:
    purpose: AI-to-AI communication, task coordination
    subdirs:
      announcements/: broadcasts to all AIs
      "{ai}/": mailbox (drafts/, instant_messaging/, note_passing/, notifications/, prompting/, saved/, tasks/)
      cline/: Cline CLI coordination (tasks/, logs/)
      claude_cli/: CLI coordination (→ ~/.claude/coordination)
      codex_cli/: Codex CLI coordination
      gemini_cli/: Gemini CLI coordination
      llama_cpp/: llama-server coordination
      counters/: atomic ID counters (*.NextId)
      orchestration/: wave orchestration

pipeline:
  flow: |
    1. Export → 10_exported/{ai}/ or _incoming/chats/{ai}/
    2. Preprocess → 20_preprocessed/
    3. Convert → 30_converted/
    4. Chunk → 40_histories/{ai}/YYYY/MM/ (terminal)
    5. Condense ON-DEMAND → chat.condensed.yml (NOT pre-stored)
    6. Extract → 60_decisions/, 60_knowledge/

symlinks:
  pattern: AI repos symlink to ai_general for shared resources
  cli_coordination: ~/.claude/coordination → ~/Documents/AI/ai_root/ai_comms/claude_cli/
  doc_versioning: "{name}.latest.{ext} → versions/{name}_v{X.Y}.{ext}"
  maintenance: canonical in versions/, .latest symlinks to current

naming:
  history_dirs: "{ai}.{YYYYMMDD}.{short_id}.{title_slug}/"
  history_files: "chunk_001.yml, chat.condensed.yml (on-demand)"
  knowledge: "know_{topic}.md"
  decisions: "decision_{date}_{topic}.md"
  docs: "{name}.latest.{ext}, {name}.latest.condensed.yml"

principles:
  - repo_isolation: each AI self-contained with symlinks to general
  - shared_resources: common in ai_general/ (instructions, specs, schemas)
  - central_pipeline: ai_memories/ processes from ANY AI, condensed ON-DEMAND
  - communication: ai_comms/ enables mailboxes, tasks, waves, atomic counters

related:
  - ai_general/docs/10_architecture/architecture_overview.latest.md
  - ai_general/docs/10_architecture/architectural_layer_model.latest.md
  - ai_general/docs/10_architecture/cli_orchestration.latest.md
  - ai_general/docs/30_protocols/protocol_taskCoordination.latest.yml
