# Tools Manifest - Single Source of Truth for AI Tool Locations
# All AI instances (Desktop Claude, CLI agents, Codex) should reference this file
# Location: ai_general/docs/20_registries/tools_manifest.yml
# Updated: 2025-12-14

metadata:
  version: "1.0.0"
  purpose: Canonical paths for all AI-accessible tools
  usage: Load this file before invoking tools by name

cli_wrappers:
  description: Shell wrappers for AI CLI instances
  base_path: ~/bin/ai/cli
  
  claude_cli:
    path: ~/bin/ai/cli/claude_cli.sh
    description: Claude CLI wrapper with tmux, agents, session management
    usage: |
      claude_cli.sh [options] "prompt"
      -t, --tmux        Run in tmux session
      -a, --auto        Skip permission prompts
      -A, --agent TYPE  Use agent (librarian, dev-lead, custodian, ops)
      -n, --named NAME  Resume named session
      -c, --continue    Continue most recent session
    examples:
      - claude_cli.sh -a -A librarian -t "Process exports"
      - claude_cli.sh -t -a -c "Continue refactoring"
  
  codex_cli:
    path: ~/bin/ai/cli/codex_cli.sh
    description: Codex CLI wrapper with tmux support
    usage: |
      codex_cli.sh [options] "prompt"
      -t, --tmux        Run in tmux session
      -a, --auto        Full auto mode (--dangerously-bypass-approvals-and-sandbox)
      -s, --session     Tmux session name
      -w, --workdir     Working directory
    examples:
      - codex_cli.sh -a -t "Review this file for errors"
      - codex_cli.sh -t -s review -a "Analyze code quality"

cli_utilities:
  description: Supporting CLI scripts
  base_path: ~/bin/ai/cli
  
  lifecycle:
    path: ~/bin/ai/cli/lifecycle/
    contents:
      - cleanup_cli_sessions.sh
      - list_cli_sessions.sh
      - launch_claude_cli_task.scpt
      - launch_codex_cli_task.scpt
  
  wrappers:
    path: ~/bin/ai/cli/wrappers/
    contents:
      - cli_script_wrapper.sh
      - cli_tmux_wrapper.sh
      - check_lock.sh
      - monitor_cli_sessions.py

python_tools:
  description: Python utilities for AI workflows
  base_path: ~/bin/all_languages/python/src
  
  todo_mgr:
    path: ~/bin/all_languages/python/src/todo_mgr/todo_mgr.py
    description: TODO system manager - kanban, status changes, queries
    usage: |
      python3 todo_mgr.py kanban
      python3 todo_mgr.py status <todo_dir> <new_status>
      python3 todo_mgr.py query --status Ready
    alias: todo  # if PATH configured

  ai_utils:
    path: ~/bin/all_languages/python/src/ai_utils/
    description: AI-specific utilities (chat processing, memory ops)
    
  doc_utils:
    path: ~/bin/all_languages/python/src/doc_utils/
    description: Document processing utilities

  yaml_utils:
    path: ~/bin/all_languages/python/src/yaml_utils/
    description: YAML manipulation utilities

chat_pipeline:
  description: Chat export/import processing
  base_path: ~/bin/ai/chat_pipeline
  
  main_scripts:
    - export_chats.py
    - preprocess_exports.py
    - convert_to_yaml.py

automation:
  description: Desktop and browser automation
  base_path: ~/bin/ai
  
  desktop_automation:
    path: ~/bin/ai/desktop_automation/
    description: AppleScript and macOS automation
    
  claude_automation:
    path: ~/bin/ai/claude_automation/
    description: Claude Desktop UI automation

paths_summary:
  # Quick reference for common operations
  invoke_claude_cli: ~/bin/ai/cli/claude_cli.sh
  invoke_codex_cli: ~/bin/ai/cli/codex_cli.sh
  run_todo_mgr: python3 ~/bin/all_languages/python/src/todo_mgr/todo_mgr.py
  list_sessions: ~/bin/ai/cli/lifecycle/list_cli_sessions.sh

notes:
  - All paths use ~ for portability (expands to /Users/shawnhillis)
  - CLI wrappers handle PATH setup internally
  - Python tools may need explicit python3 invocation
  - Codex CLI -a flag now uses --dangerously-bypass-approvals-and-sandbox (fixed 2025-12-14)
