meta: {v: 1.2.0, updated: 2026-01-12, purpose: "canonical paths for AI-accessible tools"}

overview: Single source of truth for tool locations - all AIs reference before invoking

cli_wrappers:
  base: ~/bin/ai/cli
  claude_cli.py:
    path: ~/bin/ai/cli/claude_cli.py
    invoke: "python3 ~/bin/ai/cli/claude_cli.py"
    desc: "Claude CLI with tmux, agents, session management. Bootstrap: global.md → platform/claude.md → roles/{type}/role.yml"
    flags: {-t: tmux, -a: auto, "-A TYPE": "agent (librarian, dev_lead, custodian, ops, peer_review, tester)", "-n NAME": named session, -c: continue, "-T": task mode (loads tasking.md)}
    examples: ['python3 claude_cli.py -a -A librarian -t "prompt"', 'python3 claude_cli.py -t -a -c "continue"']
    bootstrap: "Roles defined in ai_general/prompts/roles/{type}/role.yml"
  codex_cli.py:
    path: ~/bin/ai/cli/codex_cli.py
    invoke: "python3 ~/bin/ai/cli/codex_cli.py"
    desc: "OpenAI Codex CLI with tmux"
    flags: {-t: tmux, -a: "full auto (--dangerously-bypass-approvals-and-sandbox)", -s: session name, -w: workdir}
  gemini_cli.py:
    path: ~/bin/ai/cli/gemini_cli.py
    invoke: "python3 ~/bin/ai/cli/gemini_cli.py"
    desc: "Gemini CLI with tmux, wave orchestration"
    flags: {-t: tmux, -a: auto, -s: session name}

agent_shortcuts:
  note: "Convenience wrappers for specific agent profiles. Role configs in ai_general/prompts/roles/"
  librarian_gemini.sh: "Gemini librarian agent"
  custodian_claude.sh: "Claude custodian agent"
  dev_lead_claude.sh: "Claude dev-lead agent"
  ops_codex.sh: "Codex ops agent"
  peer_review_codex.sh: "Codex peer-review agent"
  tester_claude.sh: "Claude tester agent"

cli_utilities:
  lifecycle: {base: ~/bin/ai/cli/lifecycle/, scripts: [cleanup_cli_sessions.sh, list_cli_sessions.sh, launch_claude_cli_task.scpt, launch_codex_cli_task.scpt]}
  wrappers: {base: ~/bin/ai/cli/wrappers/, scripts: [cli_script_wrapper.sh, cli_tmux_wrapper.sh, check_lock.sh, monitor_cli_sessions.py]}
  wave: {scripts: [spawn_wave_librarians.sh, wave_launcher.sh, wave_monitor.sh]}

python_tools:
  base: ~/bin/all_languages/python/src
  todo_mgr:
    path: ~/bin/all_languages/python/src/todo_mgr/todo_mgr.py
    desc: "TODO system - kanban, status, queries"
    cmds: ["kanban", "status <dir> <status>", "query --status Ready"]
  other: [ai_utils/ (chat, memory), doc_utils/, yaml_utils/]

chat_pipeline:
  base: ~/bin/ai/chat_pipeline
  scripts: [export_chats.py, preprocess_exports.py, convert_to_yaml.py]

automation:
  base: ~/bin/ai
  dirs: [desktop_automation/, claude_automation/]

mcps:
  task-coord:
    path: ai_general/apps/mcps/task-coord/server.py
    type: MCP server
    purpose: "Task coordination MCP server for playbooks and task management"
    tools: [list_playbooks, get_playbook, start_playbook, stop_playbook, list_templates, gen_task, list_tasks, get_task, move_task, list_platforms]
  cli-agent:
    path: ai_general/apps/mcps/cli-agent/server.py
    type: MCP server
    purpose: "Launch and manage CLI agents with role-based bootstrapping"
    tools: [launch_agent, launch_librarian, launch_dev_lead, launch_custodian, launch_ops, launch_peer_review, launch_tester, kill, attach, send_keys, list_sessions, get_status]

quick_ref:
  claude_cli: "python3 ~/bin/ai/cli/claude_cli.py"
  codex_cli: "python3 ~/bin/ai/cli/codex_cli.py"
  gemini_cli: "python3 ~/bin/ai/cli/gemini_cli.py"
  todo_mgr: "python3 ~/bin/all_languages/python/src/todo_mgr/todo_mgr.py"
  list_sessions: ~/bin/ai/cli/lifecycle/list_cli_sessions.sh

notes:
  - "~ = /Users/shawnhillis"
  - "CLI wrappers are now Python (migrated from .sh 2026-01)"
  - "All python scripts need explicit python3"
  - "Agent shortcuts (.sh) still work for convenience"
  - "Roles moved from ~/.claude/agents.json to ai_general/prompts/roles/ (2026-01-12)"
  - "New roles: peer_review, tester added alongside librarian, dev_lead, custodian, ops"
