# Condensed: tools_manifest_v1.0.md
# Purpose: Canonical paths for AI-accessible tools

metadata:
  source_file: tools_manifest_v1.0.md
  condensed_date: 2025-12-22T10:58:00Z
  version: 1.0.0

purpose: "Single source of truth for AI tool locations"

cli_wrappers:
  base: ~/bin/ai/cli
  claude_cli.sh:
    path: ~/bin/ai/cli/claude_cli.sh
    desc: "Claude CLI wrapper with tmux, agents, sessions"
    flags: [-t tmux, -a auto, -A agent, -n named, -c continue]
  codex_cli.sh:
    path: ~/bin/ai/cli/codex_cli.sh
    desc: "Codex CLI wrapper with tmux support"
    flags: [-t tmux, -a auto, -s session, -w workdir]

cli_utilities:
  lifecycle: ~/bin/ai/cli/lifecycle/
  wrappers: ~/bin/ai/cli/wrappers/

python_tools:
  base: ~/bin/all_languages/python/src
  todo_mgr: ~/bin/all_languages/python/src/todo_mgr/todo_mgr.py
  ai_utils: ~/bin/all_languages/python/src/ai_utils/
  doc_utils: ~/bin/all_languages/python/src/doc_utils/

chat_pipeline: ~/bin/ai/chat_pipeline
automation: ~/bin/ai/desktop_automation/

quick_ref:
  invoke_claude: ~/bin/ai/cli/claude_cli.sh
  invoke_codex: ~/bin/ai/cli/codex_cli.sh
  todo_mgr: "python3 ~/bin/all_languages/python/src/todo_mgr/todo_mgr.py"
  list_sessions: ~/bin/ai/cli/lifecycle/list_cli_sessions.sh
